name: Checks
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Linter, Jest, Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: yarn install
    - name: Install Playwright Browsers
      run: yarn run playwright install --with-deps
    - name: Run linter
      run: yarn run lint
    - name: Run unit tests with jest
      run: yarn run test
    - name: Run e2e tests with playwright
      run: yarn run test:e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
